# Generated by Django 3.1.7 on 2021-03-07 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='owner',
        ),
    ]
