# Generated by Django 3.1.7 on 2021-03-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20210307_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='parent_id',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
